output "dev_public_ip" {
  description = "Public IP address of the Dev EC2 instance"
  value       = aws_instance.dev.public_ip
}

output "dev_url" {
  description = "Dev site URL"
  value       = "http://${aws_instance.dev.public_ip}/cafe"
}

output "prod_public_ip" {
  description = "Public IP of the Prod EC2 instance (copied AMI)"
  value       = aws_instance.prod.public_ip
}

output "prod_url" {
  description = "Prod site URL"
  value       = "http://${aws_instance.prod.public_ip}/cafe"
}

output "private_key_file" {
  description = "Local path to the SSH private key generated by Terraform"
  value       = local_file.private_key.filename
}